#import "lib/napkin.typ": *
#import "lib/napkin-users.typ": *

// Workaround: lib/users/ghost.json declares avatar format "jpeg",
// which Typst's image() rejects (expects "jpg").
#let ghost = (
  ..users.ghost,
  avatar: (source: users.ghost.avatar.source, format: "jpg"),
)

#plain_box(title: "AT-2.1.14")[
  Determine whether there exists a short exact sequence
  $0 -> ZZ_4 -> ZZ_8 plus.o ZZ_2 -> ZZ_4 -> 0$. More generally, determine which abelian
  groups $A$ fit into a short exact sequence $0 -> ZZ_(p^m) -> A -> ZZ_(p^n) -> 0$ with $p$
  prime. What about the case of short exact sequences $0 -> ZZ -> A -> ZZ_n -> 0$?
]

#solution(ghost)[
  #enum(numbering: "a)")[
    There exists: Let $H := chevron.l (2, 1) chevron.r subset ZZ_8 plus.o ZZ_2$ then $H$
    is cyclic group of order $4$ and $N := (ZZ_8 plus.o ZZ_2) slash H$ is cyclic group of
    order $4$ because $2(1, 0) = (2, 0) != (0, 0) space "mod" thin H$ so $(1, 0)$ is order $4$
    $"mod" thin H$. So exact sequence $0 -> H -> ZZ_8 plus.o ZZ_2 -> N -> 0$ is equivalent
    with $0 -> ZZ_4 -> ZZ_8 plus.o ZZ_2 -> ZZ_4 -> 0$, what we desire.
  ][
    I'll show that "1. $A$ is the middle term of exact sequence
    $0 -> ZZ_(p^m) -> A -> ZZ_(p^n) -> 0$" and "2. $A = ZZ_(p^k) plus.o ZZ_(p^(m+n-k))$
    for $0 <= k <= min(m, n)$".

    *(2 $==>$ 1)* Let $H = chevron.l (1, p^(n-k)) chevron.r subset A$. Then $H$ is cyclic
    group of order $p^m$. And every $(x, y) + H in A slash H$ is exact the same with
    $(0, y - p^(n-k) x) + H$ so $A slash H$ is cyclic group generated by $(0, 1) + H$.
    $p^n ((0, 1) + H) = (0, p^n) + H = (p^k, 0) + p^k (1 + p^(n-k)) + H = H$ so $A slash H$ is
    order $p^n$. Thus $A$ is the middle term of given exact sequence.

    *(1 $==>$ 2)* Let $a := f(1)$ and select $b in A$ as $g(b) := 1$ for
    $0 -> ZZ_(p^m) attach(->, t: f) A attach(->, t: g) ZZ_(p^n) -> 0$, then $A$ is generated
    by $a, b$ so $A$ must be $ZZ_(p^k) plus.o ZZ_(p^l)$ form with $k + l = m + n$ and
    $k <= l$. And order of $b := (x, y)$ cannot be less than $p^n$ because
    $g(p^(n-1) b) = p^(n-1) g(b) != 0$. So $p^n <= max("ord"(x), "ord"(y))$ therefore
    $n <= max(k, l)$ so $l >= n$. Similarly, $a := (z, w)$ is order $p^m$ so $l >= m$.
    $l >= max(n, m)$ and $k = m + n - l <= min(m, n)$ holds.
  ][
    I'll show that "1. $A$ is the middle term of exact sequence $0 -> ZZ -> A -> ZZ_n -> 0$"
    and "2. $A = ZZ_d plus.o ZZ$ for $d divides n$".

    *(2 $==>$ 1)* Let $c := n slash d$ be an positive integer and
    $pi : ZZ plus.o ZZ_d -> ZZ_n$ as $pi : (x, y) |-> x + c y$. Then its kernel is
    generated by $(c, -1)$ so it is infinite cyclic so isomorphic with $ZZ$, and $pi$ is
    surely surjective so $A$ is the middle term.

    *(1 $==>$ 2)* We can say that $A$ is generated by two elements using similar way with b)
    and $A$ must be infinite, so $A$ must be isomorphic with $ZZ plus.o ZZ_d$ (If
    $d = 0$, then $ZZ_d = ZZ$). If $N$ be infinite cyclic subgroup of $A$ with generator
    $(x, y)$ and $A slash N$ is finite cyclic of order $n$, then $(n, 0), (0, k) in N$ when
    $gcd(n, d) = k$ because $n(0, 1), n(1, 0) = (0, 0) space "mod" thin N$. Since
    $(n, 0), (0, k) != (0, 0)$, so there exists nonzero $r, s in ZZ$ with $r(n, 0) = s(0, k)$.
    This makes $r = 0$, so it cannot be. $(0, k) = (0, 0)$ holds, so $d divides k$ thus
    $d divides n$.
  ]
]
